# Generated by Django 5.1.4 on 2025-02-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('dermatology', 'Dermatology'), ('general_practice', 'General Practice'), ('psychiatry', 'Psychiatry'), ('gynecology', 'Gynecology'), ('dentistry', 'Dentistry'), ('ENT', 'Ear, Nose, and Throat'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('oncology', 'Oncology'), ('pulmonology', 'Pulmonology'), ('urology', 'Urology'), ('rheumatology', 'Rheumatology'), ('geriatrics', 'Geriatrics'), ('allergy_immunology', 'Allergy and Immunology')], max_length=100),
        ),
    ]
