# Generated by Django 5.1.4 on 2025-02-02 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient'),
        ),
    ]
